-- EL TITULO DE PELICULAS CON EL IDIOMA QUE TIENEN
SELECT SUM(language_id) AS 'FILM MISMO IDIOMA' FROM film; 
--  MONTO DE UN DIA EN ESPECIFICO
SELECT customer_id, SUM(amount) AS total_dia FROM payment WHERE payment_date BETWEEN '2005-06-15 00:00:00' AND '2005-06-15 23:59:59' GROUP BY customer_id ORDER BY total_dia DESC;

